ホーム画面・カメラ画面・画像確認画面の実装
hkuwabara-cq/FacialExpressionChampionship pull request #1
Opened 2021-08-04 15:51 UTC by hkuwabara-cq

## [アプリ設計図](https://caraquri-my.sharepoint.com/:x:/g/personal/h_kuwabara_caraquri_onmicrosoft_com/EaPbZRZOQxlHg8m4zdV4-vgBYlGo9q0t45lHUN7Sm1ojFA?e=jKtcck)

## 実装内容
### ホーム画面(UI/機能)
特筆事項なし
<img src="https://user-images.githubusercontent.com/72906152/128212598-fc18b132-234c-4f14-ac2f-15810798901b.jpg" width=300dp>
### カメラ画面(UI/機能)
<img src="https://user-images.githubusercontent.com/72906152/128212595-be1af1a2-a81a-430f-bbb4-2ca68f10c5b5.jpg" width=300dp>

### 画像確認画面(UIのみ)
<img src="https://user-images.githubusercontent.com/72906152/128212579-b76053f1-8e04-481f-b8b4-033631bc170b.jpg" width=300dp>

## 留意事項

## 確認してもらいたい点

2021-08-16 09:25 UTC, hyoshimi-cq requested changes
レビューしました！

2021-08-16 09:25 UTC, hyoshimi-cq commented on build.gradle
>          jcenter()
これ削除しておきますか

2021-08-16 09:25 UTC, hyoshimi-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/CameraFragment.kt
> +        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult? ->
この辺りのAndroid APIを呼ぶだけでアプリとはあまり関係ないロジックはExtensionに移動しちゃうのがいいと思います

 `onImageAttachmentClick()` の中身も同じように移動しちゃっていいかもですね

```kt
fun Fragment.registerForLibraryActivityResult(success: (Uri) -> Unit): ActivityResultLauncher {
  // 成功のタイミングでsuccessを呼ぶ
}

fun Fragment.openLibrary(launcher: ActivityResultLauncher) {
  ...
}
```

2021-08-16 09:25 UTC, hyoshimi-cq commented on .gitignore
>  /.idea/navEditor.xml
https://www.toptal.com/developers/gitignore
ここでgitignoreの内容を探してもいいかもですね

https://www.toptal.com/developers/gitignore/api/androidstudio,android,kotlin,java
こんな感じで表示されます

2021-08-16 09:25 UTC, hyoshimi-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +        private val themeList = listOf("怒り", "軽蔑", "嫌悪", "恐れ", "幸せ", "通常", "悲しみ", "驚き")
これはVMで持っておきたいですね
文字列ではなくresource idだとなお良しです

```kt
// VM
fun setupBattle() {
  battleTheme.set(themeList.shuffled()[0])
}
```

2021-08-16 15:18 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +    override fun onBackPressed() {}
ここはデフォルトの戻るボタンを使えないようにするために空にしてます

2021-08-16 15:19 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/CameraFragment.kt
> +import kotlinx.android.synthetic.main.fragment_camera.*
失礼しました！

2021-08-16 15:19 UTC, hkuwabara-cq commented on .gitignore
>  /.idea/navEditor.xml
すごい！これ知らなかったです！

2021-08-19 00:56 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +        ContextCompat.checkSelfPermission(this, it) == PackageManager.PERMISSION_GRANTED
移行しました！

2021-08-19 00:56 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/viewmodel/CameraViewModel.kt
> +    fun takePhoto(imageCapture: ImageCapture?, outputDirectory: File) {
移行しました！

2021-08-19 00:56 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/CameraFragment.kt
> +        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult? ->
移行しました！

2021-08-19 13:00 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/CameraFragment.kt
> +            mediaDir else requireContext().filesDir
hiltでProvideさせるようにしました！

2021-08-21 05:20 UTC, hkuwabara-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +        private val themeList = listOf("怒り", "軽蔑", "嫌悪", "恐れ", "幸せ", "通常", "悲しみ", "驚き")
VMで持たせるようにしました。
Data層に移す,subscribeするのは次のPRで対応します。

2021-09-02 12:39 UTC, hyoshimi-cq reviewed
基本的に良さそうです 👍 
気になるところをコメントしましたー

2021-09-02 12:39 UTC, hyoshimi-cq commented on app/src/main/java/com/example/facialexpressionchampionship/extension/FragmentExt.kt
> +        fragmentManager.popBackStack()
これって意味あるんですかね 🤔 

rootに戻したいのであれば
```kt
fragmentManager.popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE)
```
ですかね

2021-09-02 12:39 UTC, hyoshimi-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +    override fun onBackPressed() {}
なるほど。。。
バックボタンを使えないようにするのはあまり良くないかなー

データが消えるっていうのはHomeに戻るとですかね？

2021-09-18 06:36 UTC, hyoshimi-cq reviewed
良さそう 👍  👍  👍

2021-09-18 06:36 UTC, hyoshimi-cq commented on app/src/main/java/com/example/facialexpressionchampionship/view/BattleActivity.kt
> +        supportFragmentManager.fragments.forEach {
```kt
supportFragmentManager.fragments.any { it is CameraFragment }.take {
  showConfirmDialog()
} ?: super.onBackPressed()
```
と書けるはずー

2021-10-31 08:02 UTC, merged